In [2]:
# Import libraries

import pandas as pd 
import numpy as np 
import os

In [3]:
# Create path 
path =  r'/Users/julie.spigner/Desktop/Kiva Data Analysis'

In [4]:
path

'/Users/julie.spigner/Desktop/Kiva Data Analysis'

In [5]:
# Import dataframes 
df_loans = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'kiva_loans.csv'), index_col = False)

In [6]:
df_loc = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'kiva_mpi_region_locations.csv'), index_col = False)

## df_loans

In [7]:
# View dataframe  
df_loans.head()

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
0,653051,300.0,300.0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,12.0,12,NaN,female,irregular,2014-01-01
1,653053,575.0,575.0,Rickshaw,Transportation,to repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:51:08+00:00,2013-12-17 08:00:00+00:00,2014-01-02 09:17:23+00:00,11.0,14,NaN,"female, female",irregular,2014-01-01
2,653068,150.0,150.0,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,334.0,2014-01-01 09:58:07+00:00,2013-12-17 08:00:00+00:00,2014-01-01 16:01:36+00:00,43.0,6,"user_favorite, user_favorite",female,bullet,2014-01-01
3,653063,200.0,200.0,Embroidery,Arts,to purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 08:03:11+00:00,2013-12-24 08:00:00+00:00,2014-01-01 13:00:00+00:00,11.0,8,NaN,female,irregular,2014-01-01
4,653084,400.0,400.0,Milk Sales,Food,to purchase one buffalo.,PK,Pakistan,Abdul Hakeem,PKR,245.0,2014-01-01 11:53:19+00:00,2013-12-17 08:00:00+00:00,2014-01-01 19:18:51+00:00,14.0,16,NaN,female,monthly,2014-01-01

In [9]:
# View descriptive stats  
df_loans.describe()

,id,funded_amount,loan_amount,partner_id,term_in_months,lender_count
count,6.712050e+05,671205.000000,671205.000000,657698.000000,671205.000000,671205.000000
mean,9.932486e+05,785.995061,842.397107,178.199616,13.739022,20.590922
std,1.966113e+05,1130.398941,1198.660073,94.247581,8.598919,28.459551
min,6.530470e+05,0.000000,25.000000,9.000000,1.000000,0.000000
25%,8.230720e+05,250.000000,275.000000,126.000000,8.000000,7.000000
50%,9.927800e+05,450.000000,500.000000,145.000000,13.000000,13.000000
75%,1.163653e+06,900.000000,1000.000000,204.000000,14.000000,24.000000
max,1.340339e+06,100000.000000,100000.000000,536.000000,158.000000,2986.000000

In [10]:
# Get info 
df_loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671205 entries, 0 to 671204
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  671205 non-null  int64
 1   funded_amount       671205 non-null  float64
 2   loan_amount         671205 non-null  float64
 3   activity            671205 non-null  object
 4   sector              671205 non-null  object
 5   use                 666973 non-null  object
 6   country_code        671197 non-null  object
 7   country             671205 non-null  object
 8   region              614405 non-null  object
 9   currency            671205 non-null  object
 10  partner_id          657698 non-null  float64
 11  posted_time         671205 non-null  object
 12  disbursed_time      668809 non-null  object
 13  funded_time         622874 non-null  object
 14  term_in_months      671205 non-null  float64
 15  lender_count        671205 non-null  int64
 16  tags                499789 non-null  object
 17  borrower_genders    666984 non-null  object
 18  repayment_interval  671205 non-null  object
 19  date                671205 non-null  object
dtypes: float64(4), int64(2), object(14)
memory usage: 102.4+ MB

In [11]:
# Check for missing values 
df_loans.isnull().sum()

id                         0
funded_amount              0
loan_amount                0
activity                   0
sector                     0
use                     4232
country_code               8
country                    0
region                 56800
currency                   0
partner_id             13507
posted_time                0
disbursed_time          2396
funded_time            48331
term_in_months             0
lender_count               0
tags                  171416
borrower_genders        4221
repayment_interval         0
date                       0
dtype: int64

Notes: There are missing values in 7 columns (use, region, partner_id, disbursed_time, funded_time, tags, borrower_genders). All datatypes of missing values are strings.

In [13]:
# Check size of dataframe to see ratio of missing values compared to all records 
df_loans.shape

(671205, 20)

In [16]:
# Create a subset of missing values in df 
df_loans_nan = df_loans[df_loans['region'].isnull() == True]

In [18]:
df_loans_nan.head(50)

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
5,1080148,250.0,250.0,Services,Services,purchase leather for my business using ksh 20000.,KE,Kenya,NaN,KES,NaN,2014-01-01 10:06:19+00:00,2014-01-30 01:42:48+00:00,2014-01-29 14:14:57+00:00,4.0,6,NaN,female,irregular,2014-01-01
49,653418,450.0,450.0,General Store,Retail,to stock his store.,SV,El Salvador,NaN,USD,81.0,2014-01-02 22:17:55+00:00,2013-12-21 08:00:00+00:00,2014-01-30 00:19:42+00:00,14.0,18,"#Repeat Borrower, user_favorite",male,monthly,2014-01-02
54,653380,225.0,225.0,Food Market,Food,to purchase various seasonal items to resell: ...,SN,Senegal,NaN,XOF,108.0,2014-01-02 16:04:50+00:00,2013-12-17 08:00:00+00:00,2014-01-03 02:15:13+00:00,14.0,7,NaN,female,monthly,2014-01-02
67,1080150,125.0,125.0,Energy,Services,purchase solar lanterns for resale.,KE,Kenya,NaN,KES,NaN,2014-01-02 08:48:38+00:00,2014-01-30 01:42:21+00:00,2014-01-23 13:35:59+00:00,3.0,6,NaN,male,irregular,2014-01-02
70,653244,2000.0,2000.0,Retail,Retail,to install a display window and a sunshade for...,IQ,Iraq,NaN,USD,166.0,2014-01-02 09:15:05+00:00,2013-12-28 08:00:00+00:00,2014-01-31 16:27:13+00:00,15.0,71,"#Schooling, #Parent, #Biz Durable Asset, user_...",male,monthly,2014-01-02
99,1080153,5000.0,5000.0,Food Production/Sales,Food,hire more staff to keep up with the volume of ...,US,United States,NaN,USD,NaN,2014-01-02 20:13:47+00:00,2014-03-10 22:53:12+00:00,2014-03-11 05:53:06+00:00,30.0,261,NaN,female,monthly,2014-01-02
102,653399,3975.0,3975.0,Food Stall,Food,to buy supplies.,PE,Peru,NaN,PEN,93.0,2014-01-02 17:08:53+00:00,2013-12-16 08:00:00+00:00,2014-01-04 00:26:05+00:00,6.0,84,NaN,"female, female, female, female, female, female...",irregular,2014-01-02
111,653376,225.0,225.0,Retail,Retail,to buy various item such as incense and plasti...,SN,Senegal,NaN,XOF,108.0,2014-01-02 15:52:20+00:00,2013-12-17 08:00:00+00:00,2014-01-05 07:33:21+00:00,15.0,5,NaN,female,monthly,2014-01-02
112,653256,1925.0,2400.0,Electronics Repair,Services,to pay the annual rent for his shop,IQ,Iraq,NaN,USD,166.0,2014-01-02 09:44:10+00:00,2013-12-29 08:00:00+00:00,NaN,15.0,41,"#Single, #Supporting Family, #Eco-friendly, us...",male,monthly,2014-01-02
114,1080151,125.0,125.0,Energy,Services,buy solar lanterns for sale.,KE,Kenya,NaN,KES,NaN,2014-01-02 10:43:30+00:00,2014-01-30 01:42:13+00:00,2014-01-23 09:47:34+00:00,3.0,7,NaN,female,irregular,2014-01-02
135,653384,850.0,850.0,Blacksmith,Manufacturing,"to purchase raw materials, such as ferrous met...",SN,Senegal,NaN,XOF,108.0,2014-01-02 16:14:55+00:00,2013-12-18 08:00:00+00:00,2014-01-03 14:51:27+00:00,15.0,24,user_favorite,male,monthly,2014-01-02
140,653375,2975.0,2975.0,Food Production/Sales,Food,NaN,TZ,Tanzania,NaN,TZS,87.0,2014-01-02 15:31:52+00:00,2013-12-24 08:00:00+00:00,2014-01-22 13:42:40+00:00,10.0,110,user_favorite,NaN,monthly,2014-01-02
145,653427,1200.0,1200.0,Personal Expenses,Personal Use,NaN,PE,Peru,NaN,PEN,139.0,2014-01-02 22:43:24+00:00,2013-12-17 08:00:00+00:00,2014-02-01 23:49:27+00:00,20.0,44,"#Single, user_favorite, user_favorite",NaN,monthly,2014-01-02
157,653408,3400.0,3400.0,Clothing Sales,Clothing,"to buy t-shirts, skirts, shorts and blouses.",PE,Peru,NaN,PEN,93.0,2014-01-02 20:49:36+00:00,2013-12-19 08:00:00+00:00,2014-01-04 19:59:01+00:00,6.0,60,NaN,"female, female, female, female, female, male",irregular,2014-01-02
165,653403,2850.0,2850.0,Poultry,Agriculture,to buy chickens.,GT,Guatemala,NaN,GTQ,113.0,2014-01-02 18:21:41+00:00,2013-12-09 08:00:00+00:00,2014-01-03 18:47:01+00:00,12.0,97,"volunteer_pick, user_favorite","female, female, female, female, female, female...",monthly,2014-01-02
170,653177,4250.0,4250.0,Catering,Food,NaN,TZ,Tanzania,NaN,TZS,87.0,2014-01-02 06:46:10+00:00,2013-12-26 08:00:00+00:00,2014-01-23 16:52:15+00:00,10.0,116,"#Schooling, #Repeat Borrower, #Woman Owned Biz...",NaN,monthly,2014-01-02
186,653253,2625.0,3000.0,Grocery Store,Food,to pay the annual rent on his grocery store an...,IQ,Iraq,NaN,USD,166.0,2014-01-02 09:35:12+00:00,2013-12-29 08:00:00+00:00,NaN,15.0,72,"#First Loan, #Biz Durable Asset, #Single, user...",male,monthly,2014-01-02
195,1080149,125.0,125.0,Grocery Store,Food,ncrease my yams stock for sales,KE,Kenya,NaN,KES,NaN,2014-01-02 08:14:56+00:00,2014-01-21 21:50:36+00:00,2014-01-16 13:36:43+00:00,3.0,6,NaN,female,irregular,2014-01-02
200,653236,2000.0,2000.0,Grocery Store,Food,to renovate his grocery store by installing ne...,IQ,Iraq,NaN,USD,166.0,2014-01-02 08:57:30+00:00,2013-12-28 08:00:00+00:00,2014-02-01 00:06:27+00:00,15.0,59,"volunteer_pick, #Job Creator, #Biz Durable Ass...",male,monthly,2014-01-02
202,653360,500.0,500.0,General Store,Retail,"to buy beans, oil, sugar, coffee, sweets, soft...",SV,El Salvador,NaN,USD,81.0,2014-01-02 14:31:22+00:00,2013-12-03 08:00:00+00:00,2014-01-22 16:12:15+00:00,14.0,12,"#Woman Owned Biz, user_favorite",female,monthly,2014-01-02
205,653389,125.0,125.0,Poultry,Agriculture,to purchase chicks to raise and resell,SN,Senegal,NaN,XOF,108.0,2014-01-02 16:27:24+00:00,2013-12-18 08:00:00+00:00,2014-01-02 18:33:06+00:00,15.0,5,NaN,male,monthly,2014-01-02
215,653374,500.0,500.0,Personal Housing Expenses,Housing,"to buy cement, iron, and hurricane fencing",SV,El Salvador,NaN,USD,81.0,2014-01-02 15:26:40+00:00,2013-12-03 08:00:00+00:00,2014-01-14 16:10:48+00:00,14.0,19,"volunteer_like, #Supporting Family",male,monthly,2014-01-02
222,653232,2400.0,2400.0,Grocery Store,Food,to pay the annual rent for his grocery store a...,IQ,Iraq,NaN,USD,166.0,2014-01-02 08:49:15+00:00,2013-12-27 08:00:00+00:00,2014-01-31 01:01:25+00:00,15.0,83,"volunteer_pick, #Single, #Supporting Family, u...",male,monthly,2014-01-02
231,1080154,10000.0,10000.0,Food Production/Sales,Food,outfit my new kitchen so that I can expand my ...,US,United States,NaN,USD,NaN,2014-01-02 21:46:47+00:00,2014-02-20 04:08:11+00:00,2014-02-20 12:08:03+00:00,36.0,280,NaN,female,monthly,2014-01-02
232,653226,3000.0,3000.0,Mobile Phones,Retail,to pay the annual rent of his shop.,IQ,Iraq,NaN,USD,166.0,2014-01-02 08:34:46+00:00,2013-12-26 08:00:00+00:00,2014-01-31 02:36:23+00:00,15.0,106,"#Parent, user_favorite",male,monthly,2014-01-02
233,653221,3000.0,3000.0,Grocery Store,Food,to renovate his grocery store and to buy more ...,IQ,Iraq,NaN,USD,166.0,2014-01-02 08:28:49+00:00,2013-12-26 08:00:00+00:00,2014-01-30 03:34:05+00:00,15.0,97,"#First Loan, #Supporting Family, user_favorite",male,monthly,2014-01-02
240,653422,1025.0,1025.0,Retail,Retail,to buy drinks and sweets.,PE,Peru,NaN,PEN,93.0,2014-01-02 22:25:55+00:00,2013-12-23 08:00:00+00:00,2014-01-03 17:36:54+00:00,6.0,31,"volunteer_pick, volunteer_like","female, female, female, male, female, female",irregular,2014-01-02
255,653425,300.0,300.0,Fruits & Vegetables,Food,to buy fruit and vegetables wholesale like ora...,SV,El Salvador,NaN,USD,81.0,2014-01-02 22:35:07+00:00,2013-12-21 08:00:00+00:00,2014-01-03 05:26:13+00:00,11.0,12,user_favorite,female,monthly,2014-01-02
273,653412,375.0,375.0,Clothing Sales,Clothing,"to buy shirts, blouses, pants, and skirts.",SV,El Salvador,NaN,USD,167.0,2014-01-02 21:40:43+00:00,2013-12-12 08:00:00+00:00,2014-01-19 07:55:53+00:00,14.0,15,"volunteer_like, user_favorite",female,monthly,2014-01-02
277,653361,500.0,500.0,Metal Shop,Manufacturing,"to buy more material such as iron, metals, lam...",SV,El Salvador,NaN,USD,81.0,2014-01-02 14:40:10+00:00,2013-12-03 08:00:00+00:00,2014-01-02 20:33:39+00:00,14.0,18,NaN,male,monthly,2014-01-02
302,653421,375.0,375.0,Food Production/Sales,Food,"to buy corn, elote (corn on the cob), milk, co...",SV,El Salvador,NaN,USD,81.0,2014-01-02 22:23:58+00:00,2013-12-21 08:00:00+00:00,2014-01-03 22:16:41+00:00,12.0,15,"volunteer_pick, volunteer_like",female,monthly,2014-01-02
309,653259,2750.0,3000.0,Grocery Store,Food,to install a new floor in his grocery store an...,IQ,Iraq,NaN,USD,166.0,2014-01-02 09:51:47+00:00,2013-12-30 08:00:00+00:00,NaN,15.0,44,"#Biz Durable Asset, #Supporting Family, user_f...",male,monthly,2014-01-02
311,1080152,125.0,125.0,Energy,Services,purchase solar lanterns.,KE,Kenya,NaN,KES,NaN,2014-01-02 11:26:51+00:00,2014-01-30 01:42:16+00:00,2014-01-23 13:10:14+00:00,3.0,4,NaN,female,irregular,2014-01-02
318,653433,1500.0,1500.0,Furniture Making,Manufacturing,"to buy wood, nails, varnish, paint, etc.",SV,El Salvador,NaN,USD,81.0,2014-01-02 23:43:58+00:00,2013-12-28 08:00:00+00:00,2014-01-05 02:37:40+00:00,20.0,55,#Parent,male,monthly,2014-01-02
349,653228,3000.0,3000.0,Mobile Phones,Retail,to install new aluminum shelves in his shop an...,IQ,Iraq,NaN,USD,166.0,2014-01-02 08:41:18+00:00,2013-12-26 08:00:00+00:00,2014-01-31 21:57:05+00:00,15.0,102,"#Parent, #Biz Durable Asset, user_favorite",male,monthly,2014-01-02
355,653426,300.0,300.0,Clothing Sales,Clothing,to buy clothes at wholesale.,SV,El Salvador,NaN,USD,81.0,2014-01-02 22:41:07+00:00,2013-12-26 08:00:00+00:00,2014-01-04 20:05:21+00:00,15.0,3,NaN,female,monthly,2014-01-02
362,653365,1025.0,1025.0,Bakery,Food,"to buy flour, butter, and dough.",SV,El Salvador,NaN,USD,81.0,2014-01-02 14:49:07+00:00,2013-12-03 08:00:00+00:00,2014-01-20 22:01:03+00:00,14.0,31,"#Parent, #Woman Owned Biz, user_favorite",female,monthly,2014-01-02
365,653239,1800.0,1800.0,Grocery Store,Food,to install some new blocks on the floor of his...,IQ,Iraq,NaN,USD,166.0,2014-01-02 09:05:18+00:00,2013-12-28 08:00:00+00:00,2014-02-01 03:17:31+00:00,15.0,67,"volunteer_pick, #Supporting Family, user_favor...",male,monthly,2014-01-02
374,653423,700.0,700.0,Retail,Retail,"Buy piñatas, beauty products, toys, hair produ...",SV,El Salvador,NaN,USD,81.0,2014-01-02 22:31:00+00:00,2013-12-28 08:00:00+00:00,2014-01-15 09:20:58+00:00,9.0,26,#Parent,female,irregular,2014-01-02
381,653756,500.0,500.0,Personal Housing Expenses,Housing,"to buy cement, sand and gravel to install a co...",SV,El Salvador,NaN,USD,81.0,2014-01-03 20:21:13+00:00,2013-12-10 08:00:00+00:00,2014-01-31 06:35:56+00:00,14.0,19,user_favorite,male,monthly,2014-01-03
387,653786,100.0,100.0,Home Energy,Personal Use,To buy a solar lamp,SV,El Salvador,NaN,USD,81.0,2014-01-03 22:10:11+00:00,2013-12-16 08:00:00+00:00,2014-01-04 21:03:38+00:00,14.0,3,NaN,female,monthly,2014-01-03
392,653782,100.0,100.0,Home Energy,Personal Use,to buy a solar lamp.,SV,El Salvador,NaN,USD,81.0,2014-01-03 21:59:03+00:00,2013-12-16 08:00:00+00:00,2014-01-04 03:31:40+00:00,14.0,4,NaN,male,monthly,2014-01-03
396,653462,400.0,400.0,Agriculture,Agriculture,"to improve her land and purchase fertilisers, ...",SV,El Salvador,NaN,USD,81.0,2014-01-03 01:10:25+00:00,2013-12-28 08:00:00+00:00,2014-01-03 10:56:12+00:00,9.0,14,NaN,female,bullet,2014-01-03
397,653750,350.0,350.0,Personal Housing Expenses,Housing,"to purchase cement, sand, iron, brick, and woo...",SV,El Salvador,NaN,USD,81.0,2014-01-03 18:11:23+00:00,2013-12-13 08:00:00+00:00,2014-01-05 18:17:18+00:00,14.0,9,NaN,female,monthly,2014-01-03
401,653788,100.0,100.0,Home Energy,Personal Use,to buy a solar lamp.,SV,El Salvador,NaN,USD,81.0,2014-01-03 22:16:41+00:00,2013-12-16 08:00:00+00:00,2014-01-04 14:35:25+00:00,14.0,1,NaN,female,monthly,2014-01-03
405,653770,100.0,100.0,Home Energy,Personal Use,to buy a solar-powered lamp.,SV,El Salvador,NaN,USD,81.0,2014-01-03 21:26:35+00:00,2013-12-16 08:00:00+00:00,2014-01-04 01:44:58+00:00,14.0,4,NaN,male,monthly,2014-01-03
407,653796,700.0,700.0,General Store,Retail,"to buy eggs, cereal, snacks, oil, pasta, deter...",SV,El Salvador,NaN,USD,81.0,2014-01-03 22:41:05+00:00,2013-12-13 08:00:00+00:00,2014-01-04 20:05:20+00:00,11.0,4,NaN,female,monthly,2014-01-03
412,653513,2350.0,2350.0,Beauty Salon,Services,NaN,TZ,Tanzania,NaN,TZS,87.0,2014-01-03 05:08:11+00:00,2013-12-31 08:00:00+00:00,2014-01-21 15:33:01+00:00,10.0,75,"user_favorite, #Parent, #Woman Owned Biz, user...",NaN,monthly,2014-01-03
414,653775,725.0,725.0,Agriculture,Agriculture,NaN,SV,El Salvador,NaN,USD,199.0,2014-01-03 21:41:23+00:00,2013-12-16 08:00:00+00:00,2014-01-28 17:28:43+00:00,20.0,19,"#Animals, #Repeat Borrower, #Schooling, user_f...",NaN,monthly,2014-01-03
416,653599,175.0,175.0,Retail,Retail,to buy dyed fabrics and cosmetics,SN,Senegal,NaN,XOF,108.0,2014-01-03 08:54:26+00:00,2013-12-19 08:00:00+00:00,2014-01-03 17:43:22+00:00,15.0,7,NaN,female,monthly,2014-01-03

Notes: This tells me that missing values in region column is not country-specific. In other words, missing labels of regions occur across multiple countries.

In [19]:
# Find duplicates 
df_loans_dups = df_loans[df_loans.duplicated()]

In [20]:
# Check for duplicates 
df_loans_dups

Empty DataFrame
Columns: [id, funded_amount, loan_amount, activity, sector, use, country_code, country, region, currency, partner_id, posted_time, disbursed_time, funded_time, term_in_months, lender_count, tags, borrower_genders, repayment_interval, date]
Index: []

Notes: There are no duplicates.

In [21]:
# View dataframe with more rows 
df_loans.head(100)

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
0,653051,300.0,300.0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,12.0,12,NaN,female,irregular,2014-01-01
1,653053,575.0,575.0,Rickshaw,Transportation,to repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:51:08+00:00,2013-12-17 08:00:00+00:00,2014-01-02 09:17:23+00:00,11.0,14,NaN,"female, female",irregular,2014-01-01
2,653068,150.0,150.0,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,334.0,2014-01-01 09:58:07+00:00,2013-12-17 08:00:00+00:00,2014-01-01 16:01:36+00:00,43.0,6,"user_favorite, user_favorite",female,bullet,2014-01-01
3,653063,200.0,200.0,Embroidery,Arts,to purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 08:03:11+00:00,2013-12-24 08:00:00+00:00,2014-01-01 13:00:00+00:00,11.0,8,NaN,female,irregular,2014-01-01
4,653084,400.0,400.0,Milk Sales,Food,to purchase one buffalo.,PK,Pakistan,Abdul Hakeem,PKR,245.0,2014-01-01 11:53:19+00:00,2013-12-17 08:00:00+00:00,2014-01-01 19:18:51+00:00,14.0,16,NaN,female,monthly,2014-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,653381,325.0,325.0,Food Market,Food,"to purchase more red oil, imported oil, rice, ...",LR,Liberia,Caldwell,LRD,182.0,2014-01-02 16:09:14+00:00,2013-12-18 08:00:00+00:00,2014-01-04 22:05:18+00:00,11.0,10,NaN,female,irregular,2014-01-02
96,653107,325.0,325.0,General Store,Retail,to buy additional stocks for her sari-sari store.,PH,Philippines,Plaridel-Cebulin,PHP,126.0,2014-01-02 01:01:10+00:00,2013-12-03 08:00:00+00:00,2014-01-02 14:24:58+00:00,11.0,10,"#Elderly, #Schooling, #Woman Owned Biz",female,irregular,2014-01-02
97,653217,2200.0,2200.0,Pharmacy,Health,"to buy medicines, sand and sacks of cement.",TZ,Tanzania,Dar es Salaam,TZS,87.0,2014-01-02 08:19:38+00:00,2013-12-17 08:00:00+00:00,2014-01-03 23:17:08+00:00,8.0,77,user_favorite,"male, female, male, male",irregular,2014-01-02
98,653345,600.0,600.0,Fruits & Vegetables,Food,"to purchase onions, tomatoes, vegetables, and ...",KE,Kenya,Likoni,KES,164.0,2014-01-02 13:55:18+00:00,2013-12-14 08:00:00+00:00,2014-01-08 22:25:13+00:00,14.0,22,NaN,female,irregular,2014-01-02
99,1080153,5000.0,5000.0,Food Production/Sales,Food,hire more staff to keep up with the volume of ...,US,United States,NaN,USD,NaN,2014-01-02 20:13:47+00:00,2014-03-10 22:53:12+00:00,2014-03-11 05:53:06+00:00,30.0,261,NaN,female,monthly,2014-01-02

In [23]:
# View names of columns in the dataframe 
df_loans.columns

Index(['id', 'funded_amount', 'loan_amount', 'activity', 'sector', 'use',
       'country_code', 'country', 'region', 'currency', 'partner_id',
       'posted_time', 'disbursed_time', 'funded_time', 'term_in_months',
       'lender_count', 'tags', 'borrower_genders', 'repayment_interval',
       'date'],
      dtype='object')

Notes: df_loans looks good. All datatypes are clarified. No critical missing values need to be addressed. All columns are labeled correctly. There are no duplicates.

## df_loc

In [26]:
# View dataframe 
df_loc.head(50)

,LocationName,ISO,country,region,world_region,MPI,geo,lat,lon
0,"Badakhshan, Afghanistan",AFG,Afghanistan,Badakhshan,South Asia,0.387,"(36.7347725, 70.81199529999999)",36.734772,70.811995
1,"Badghis, Afghanistan",AFG,Afghanistan,Badghis,South Asia,0.466,"(35.1671339, 63.7695384)",35.167134,63.769538
2,"Baghlan, Afghanistan",AFG,Afghanistan,Baghlan,South Asia,0.300,"(35.8042947, 69.2877535)",35.804295,69.287754
3,"Balkh, Afghanistan",AFG,Afghanistan,Balkh,South Asia,0.301,"(36.7550603, 66.8975372)",36.755060,66.897537
4,"Bamyan, Afghanistan",AFG,Afghanistan,Bamyan,South Asia,0.325,"(34.8100067, 67.8212104)",34.810007,67.821210
5,"Daykundi, Afghanistan",AFG,Afghanistan,Daykundi,South Asia,0.313,"(33.669495, 66.0463534)",33.669495,66.046353
6,"Farah, Afghanistan",AFG,Afghanistan,Farah,South Asia,0.319,"(32.4464635, 62.1454133)",32.446464,62.145413
7,"Faryab, Afghanistan",AFG,Afghanistan,Faryab,South Asia,0.250,"(36.0795613, 64.90595499999999)",36.079561,64.905955
8,"Ghazni, Afghanistan",AFG,Afghanistan,Ghazni,South Asia,0.245,"(33.5450587, 68.4173972)",33.545059,68.417397
9,"Ghor, Afghanistan",AFG,Afghanistan,Ghor,South Asia,0.384,"(34.0995776, 64.90595499999999)",34.099578,64.905955
10,"Helmand, Afghanistan",AFG,Afghanistan,Helmand,South Asia,0.261,"(31.3636474, 63.95861110000001)",31.363647,63.958611
11,"Herat, Afghanistan",AFG,Afghanistan,Herat,South Asia,0.353,"(11.6155109, 104.3791912)",11.615511,104.379191
12,"Jawzjan, Afghanistan",AFG,Afghanistan,Jawzjan,South Asia,0.293,"(36.8969692, 65.6658568)",36.896969,65.665857
13,"Kabul, Afghanistan",AFG,Afghanistan,Kabul,South Asia,0.117,"(34.5553494, 69.207486)",34.555349,69.207486
14,"Kandahar, Afghanistan",AFG,Afghanistan,Kandahar,South Asia,0.437,"(31.628871, 65.7371749)",31.628871,65.737175
15,"Kapisa, Afghanistan",AFG,Afghanistan,Kapisa,South Asia,0.280,"(34.9810572, 69.6214562)",34.981057,69.621456
16,"Khost, Afghanistan",AFG,Afghanistan,Khost,South Asia,0.296,"(33.3338472, 69.9371673)",33.333847,69.937167
17,"Kunarha, Afghanistan",AFG,Afghanistan,Kunarha,South Asia,0.269,"(34.8465893, 71.097317)",34.846589,71.097317
18,"Kunduz, Afghanistan",AFG,Afghanistan,Kunduz,South Asia,0.294,"(36.7285907, 68.8680663)",36.728591,68.868066
19,"Laghman, Afghanistan",AFG,Afghanistan,Laghman,South Asia,0.369,"(34.6897687, 70.1455805)",34.689769,70.145581
20,"Logar, Afghanistan",AFG,Afghanistan,Logar,South Asia,0.187,"(34.0145518, 69.1923916)",34.014552,69.192392
21,"Nangarhar, Afghanistan",AFG,Afghanistan,Nangarhar,South Asia,0.287,"(34.1718313, 70.6216794)",34.171831,70.621679
22,"Nimroz, Afghanistan",AFG,Afghanistan,Nimroz,South Asia,0.231,"(31.0261488, 62.4504154)",31.026149,62.450415
23,"Nooristan, Afghanistan",AFG,Afghanistan,Nooristan,South Asia,0.611,"(35.3250223, 70.90712359999999)",35.325022,70.907124
24,"Paktika, Afghanistan",AFG,Afghanistan,Paktika,South Asia,0.137,"(32.2645386, 68.52471489999999)",32.264539,68.524715
25,"Paktya, Afghanistan",AFG,Afghanistan,Paktya,South Asia,0.218,"(33.706199, 69.3831079)",33.706199,69.383108
26,"Panjsher, Afghanistan",AFG,Afghanistan,Panjsher,South Asia,0.120,"(35.5025772, 69.9550338)",35.502577,69.955034
27,"Parwan, Afghanistan",AFG,Afghanistan,Parwan,South Asia,0.294,"(34.9630977, 68.81088489999999)",34.963098,68.810885
28,"Samangan, Afghanistan",AFG,Afghanistan,Samangan,South Asia,0.350,"(35.9807296, 67.57085359999999)",35.980730,67.570854
29,"Sar-E-Pul, Afghanistan",AFG,Afghanistan,Sar-E-Pul,South Asia,0.341,"(35.6707473, 66.0463534)",35.670747,66.046353
30,"Takhar, Afghanistan",AFG,Afghanistan,Takhar,South Asia,0.361,"(36.6698013, 69.4784541)",36.669801,69.478454
31,"Urozgan, Afghanistan",AFG,Afghanistan,Urozgan,South Asia,0.624,"(32.9271287, 66.1415263)",32.927129,66.141526
32,"Wardak, Afghanistan",AFG,Afghanistan,Wardak,South Asia,0.340,"(34.3513494, 68.2385339)",34.351349,68.238534
33,"Zabul, Afghanistan",AFG,Afghanistan,Zabul,South Asia,0.175,"(32.1918782, 67.1894488)",32.191878,67.189449
34,NaN,ALB,Albania,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
35,NaN,ARM,Armenia,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
36,NaN,AZE,Azerbaijan,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
37,"Bujumbura Mairie, Burundi",BDI,Burundi,Bujumbura Mairie,Sub-Saharan Africa,0.164,"(-3.4146958, 29.3598782)",-3.414696,29.359878
38,"Nord, Burundi",BDI,Burundi,Nord,Sub-Saharan Africa,0.501,"(-3.373056, 29.918886)",-3.373056,29.918886
39,"Centre-Est, Burundi",BDI,Burundi,Centre-Est,Sub-Saharan Africa,0.473,"(9.0630743, 7.464915)",9.063074,7.464915
40,"Ouest, Burundi",BDI,Burundi,Ouest,Sub-Saharan Africa,0.499,"(-3.373056, 29.918886)",-3.373056,29.918886
41,"Sud, Burundi",BDI,Burundi,Sud,Sub-Saharan Africa,0.422,"(14.6090537, 121.0222565)",14.609054,121.022256
42,"Alibori, Benin",BEN,Benin,Alibori,Sub-Saharan Africa,0.528,"(10.9681093, 2.7779813)",10.968109,2.777981
43,"Atacora, Benin",BEN,Benin,Atacora,Sub-Saharan Africa,0.454,"(10.7954931, 1.6760691)",10.795493,1.676069
44,"Atlantique, Benin",BEN,Benin,Atlantique,Sub-Saharan Africa,0.278,"(6.6588391, 2.2236667)",6.658839,2.223667
45,"Borgou, Benin",BEN,Benin,Borgou,Sub-Saharan Africa,0.351,"(9.5340864, 2.7779813)",9.534086,2.777981
46,"Collines, Benin",BEN,Benin,Collines,Sub-Saharan Africa,0.292,"(13.718252, -2.302446)",13.718252,-2.302446
47,"Couffo, Benin",BEN,Benin,Couffo,Sub-Saharan Africa,0.345,"(7.003589400000001, 1.7538817)",7.003589,1.753882
48,"Donga, Benin",BEN,Benin,Donga,Sub-Saharan Africa,0.335,"(9.7191867, 1.6760691)",9.719187,1.676069
49,"Littoral, Benin",BEN,Benin,Littoral,Sub-Saharan Africa,0.083,"(6.3806973, 2.4406387)",6.380697,2.440639

In [27]:
# Check size of the dataframe 
df_loc.shape

(2772, 9)

Notes: This dataframe--df_loc--is much smaller compared to df_loans.

In [29]:
# Gather information 
df_loc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2772 entries, 0 to 2771
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationName  984 non-null    object
 1   ISO           1008 non-null   object
 2   country       1008 non-null   object
 3   region        984 non-null    object
 4   world_region  1008 non-null   object
 5   MPI           984 non-null    float64
 6   geo           2772 non-null   object
 7   lat           892 non-null    float64
 8   lon           892 non-null    float64
dtypes: float64(3), object(6)
memory usage: 195.0+ KB

Notes: All datatypes are labeled correctly.

In [30]:
# Check for missing values 
df_loc.isnull().sum()

LocationName    1788
ISO             1764
country         1764
region          1788
world_region    1764
MPI             1788
geo                0
lat             1880
lon             1880
dtype: int64

Notes: There are multiple missing values in all columns except for one (geo). There are only 2,772 rows in the entire dataframe. This means more than half of the dataframe is missing. For reference: 1,386 is half of 2,772. However, the geo column is the most important one and can be used to fill in missing values in some columns. I'm going to take a closer look at the geo column based on missing values in region column to see if this is true.

In [31]:
# Create a subset to find missing values 
df_loc_nan = df_loc[df_loc['region'].isnull() == True]

In [33]:
df_loc_nan.head(25)

,LocationName,ISO,country,region,world_region,MPI,geo,lat,lon
34,NaN,ALB,Albania,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
35,NaN,ARM,Armenia,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
36,NaN,AZE,Azerbaijan,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
74,NaN,BIH,Bosnia and Herzegovina,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
118,NaN,BRB,Barbados,NaN,Latin America and Caribbean,NaN,"(1000.0, 1000.0)",NaN,NaN
234,NaN,DZA,Algeria,NaN,Arab States,NaN,"(1000.0, 1000.0)",NaN,NaN
413,NaN,IND,India,NaN,South Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
449,NaN,KAZ,Kazakhstan,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
458,NaN,KGZ,Kyrgyzstan,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
510,NaN,LCA,Saint Lucia,NaN,Latin America and Caribbean,NaN,"(1000.0, 1000.0)",NaN,NaN
535,NaN,MDA,"Moldova, Republic of",NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
558,NaN,MDV,Maldives,NaN,South Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
559,NaN,MEX,Mexico,NaN,Latin America and Caribbean,NaN,"(1000.0, 1000.0)",NaN,NaN
560,NaN,MKD,"Macedonia, The former Yugoslav Republic of",NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
582,NaN,MNE,Montenegro,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
781,NaN,PSE,"Palestine, State ofa",NaN,Arab States,NaN,"(1000.0, 1000.0)",NaN,NaN
837,NaN,SOM,Somalia,NaN,Arab States,NaN,"(1000.0, 1000.0)",NaN,NaN
838,NaN,SRB,Serbia,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
907,NaN,THA,Thailand,NaN,East Asia and the Pacific,NaN,"(1000.0, 1000.0)",NaN,NaN
913,NaN,TKM,Turkmenistan,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
932,NaN,TUN,Tunisia,NaN,Arab States,NaN,"(1000.0, 1000.0)",NaN,NaN
952,NaN,UKR,Ukraine,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
965,NaN,VUT,Vanuatu,NaN,East Asia and the Pacific,NaN,"(1000.0, 1000.0)",NaN,NaN
987,NaN,ZAF,South Africa,NaN,Sub-Saharan Africa,NaN,"(1000.0, 1000.0)",NaN,NaN
1008,NaN,NaN,NaN,NaN,NaN,NaN,"(1000.0, 1000.0)",NaN,NaN

Notes: Apparently (1000.0, 1000.0) is considered a missing value in geo column. Check to see how many values in geo column with records of this.

In [34]:
# Find specific cells in a column 
df_loc.loc[df_loc['geo'] == '(1000.0, 1000.0)']

,LocationName,ISO,country,region,world_region,MPI,geo,lat,lon
34,NaN,ALB,Albania,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
35,NaN,ARM,Armenia,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
36,NaN,AZE,Azerbaijan,NaN,Europe and Central Asia,NaN,"(1000.0, 1000.0)",NaN,NaN
51,"Ouðmð, Benin",BEN,Benin,Ouðmð,Sub-Saharan Africa,0.238,"(1000.0, 1000.0)",NaN,NaN
63,"Nord, Burkina Faso",BFA,Burkina Faso,Nord,Sub-Saharan Africa,0.581,"(1000.0, 1000.0)",NaN,NaN
...,...,...,...,...,...,...,...,...,...
2767,NaN,NaN,NaN,NaN,NaN,NaN,"(1000.0, 1000.0)",NaN,NaN
2768,NaN,NaN,NaN,NaN,NaN,NaN,"(1000.0, 1000.0)",NaN,NaN
2769,NaN,NaN,NaN,NaN,NaN,NaN,"(1000.0, 1000.0)",NaN,NaN
2770,NaN,NaN,NaN,NaN,NaN,NaN,"(1000.0, 1000.0)",NaN,NaN
2771,NaN,NaN,NaN,NaN,NaN,NaN,"(1000.0, 1000.0)",NaN,NaN

In [35]:
# Command pandas not to assign any options regarding the max number of rows to display 
pd.options.display.max_rows = None

In [36]:
# Find specific cells in a column 
df_loc.loc[df_loc['geo'] == '(1000.0, 1000.0)']

                                           LocationName  ISO  \
34                                                  NaN  ALB
35                                                  NaN  ARM
36                                                  NaN  AZE
51                                         Ouðmð, Benin  BEN
63                                   Nord, Burkina Faso  BFA
74                                                  NaN  BIH
86              Potosð, Bolivia, Plurinational State of  BOL
93                                        Amapð, Brazil  BRA
98                               Espðrito Santo, Brazil  BRA
99                                        Goiðs, Brazil  BRA
104                                      Paranð, Brazil  BRA
105                                     Paraðba, Brazil  BRA
106                                        Parð, Brazil  BRA
108                                       Piauð, Brazil  BRA
118                                                 NaN  BRB
141              Nana-Mambðrð, Central African Republic  CAF
143               Ouham-Pendð, Central African Republic  CAF
145                      Kðmo, Central African Republic  CAF
146              Nana-Grðbizi, Central African Republic  CAF
158                           Centre-Est, Cote d'Ivoire  CIV
160                         Centre-Ouest, Cote d'Ivoire  CIV
165                     Sud sans Abidjan, Cote d'Ivoire  CIV
169                     Centre (sans Yaoundð), Cameroon  CMR
172                              Extrðme-Nord, Cameroon  CMR
179                                   Yaoundð, Cameroon  CMR
183         ðquateur, Congo, Democratic Republic of the  COD
184   Kasað-Occidental, Congo, Democratic Republic o...  COD
185   Kasað-Oriental, Congo, Democratic Republic of the  COD
188        Nord-Kivu, Congo, Democratic Republic of the  COD
193                        Lðkoumou, Congo, Republic of  COG
194                         Bouenza, Congo, Republic of  COG
211                Caldas, Risaralda, Quindio, Colombia  COL
212                    Tolima, Huila, Caqueta, Colombia  COL
214                 Valle Sin Cali Ni Litoral, Colombia  COL
215                Cauca Y Nariðo Sin Litoral, Colombia  COL
220             Ndzuwani (Ndzouani or Anjouan), Comoros  COM
223                           Other Districts, Djibouti  DJI
224                  Cibao Nordeste, Dominican Republic  DOM
234                                                 NaN  DZA
245                                      Sharkia, Egypt  EGY
277                                  Haut-Ogoouð, Gabon  GAB
278                                 Moyen-Ogoouð, Gabon  GAB
279                                      Ngounið, Gabon  GAB
281           Ogoouð Maritime (sans Port-Gentil), Gabon  GAB
282                                Ogoouð-Ivindo, Gabon  GAB
283                                  Ogoouð-Lolo, Gabon  GAB
284                                  Woleu-Nðtem, Gabon  GAB
295                                        Bokð, Guinea  GIN
300                                        Labð, Guinea  GIN
302                                  N'Zðrðkorð, Guinea  GIN
307                                     Kerewan, Gambia  GMB
319                                  Sab, Guinea-Bissau  GNB
345                            Demerara-Mahaica, Guyana  GUY
352                                 Atlðntida, Honduras  HND
353                                     Colðn, Honduras  HND
356                                    Cortðs, Honduras  HND
358                                El Paraðso, Honduras  HND
359                         Francisco Morazðn, Honduras  HND
361                                  Intibucð, Honduras  HND
362                         Islas de la Bahða, Honduras  HND
367                             Santa Bðrbara, Honduras  HND
370              Aire Mðtropolitaine/Reste-Ouest, Haiti  HTI
413                                                 NaN  IND
444                                  Clarendon, Jamaica  JAM
449                                                 NaN  KAZ
458                                                 NaN  KGZ
460                       Battambang & Pailin, Cambodia  KHM
472               Preah Vihear & Steung Treng, Cambodia  KHM
502                                       Lofa, Liberia  LBR
510                                                 NaN  LCA
526                            Rðgion Oriental, Morocco  MAR
535                                                 NaN  MDA
541                       Anamoroni'i Mania, Madagascar  MDG
558                                                 NaN  MDV
559                                                 NaN  MEX
560                                                 NaN  MKD
564                                         Sðgou, Mali  MLI
582                                                 NaN  MNE
591                                Zambðzia, Mozambique  MOZ
599                            Hodh Charghy, Mauritania  MRT
613                              Blantyre Rural, Malawi  MWI
628                                      Mwanza, Malawi  MWI
677                                  FCT-Abuja, Nigeria  NGA
692                                Cross River, Nigeria  NGA
713                                   Carazo, Nicaragua  NIC
726                             Far-WesternTerai, Nepal  NPL
730                                Western  Hill, Nepal  NPL
740                                        ðncash, Peru  PER
741                                      Apurðmac, Peru  PER
748                                       Huðnuco, Peru  PER
750                                         Junðn, Peru  PER
760                                    San Martðn, Peru  PER
781                                                 NaN  PSE
788                               Central Darfor, Sudan  SDN
793                                     Khartoum, Sudan  SDN
802                                  West Darfor, Sudan  SDN
837                                                 NaN  SOM
838                                                 NaN  SRB
840                      Jonglei and Unity, South Sudan  SSD
850           Regio Norte Oeste, Sao Tome and Principe  STP
872                          Edlb, Syrian Arab Republic  SYR
879                      Qonitara, Syrian Arab Republic  SYR
885                                         GuðRa, Chad  TCD
895                                     N'DjamðNa, Chad  TCD
896                                       Ouaddað, Chad  TCD
897                                       Salamat, Chad  TCD
907                                                 NaN  THA
913                                                 NaN  TKM
924                               Manatuto, Timor-Leste  TLS
932                                                 NaN  TUN
952                                                 NaN  UKR
958                                Tashkent, Uzbekistan  UZB
960       Northern Midlands and Mountain area, Viet Nam  VNM
965                                                 NaN  VUT
985                                     Aldhalae, Yemen  YEM
987                                                 NaN  ZAF
1008                                                NaN  NaN
1009                                                NaN  NaN
1010                                                NaN  NaN
1011                                                NaN  NaN
1012                                                NaN  NaN
1013                                                NaN  NaN
1014                                                NaN  NaN
1015                                                NaN  NaN
1016                                                NaN  NaN
1017                                                NaN  NaN
1018                                                NaN  NaN
1019                                                NaN  NaN
1020                                                NaN  NaN
1021                                                NaN  NaN
1022                                                NaN  NaN
1023                                                NaN  NaN
1024                                                NaN  NaN
1025                                                NaN  NaN
1026                                                NaN  NaN
1027                                                NaN  NaN
1028                                                NaN  NaN
1029                                                NaN  NaN
1030                                                NaN  NaN
1031                                                NaN  NaN
1032                                                NaN  NaN
1033                                                NaN  NaN
1034                                                NaN  NaN
1035                                                NaN  NaN
1036                                                NaN  NaN
1037                                                NaN  NaN
1038                                                NaN  NaN
1039                                                NaN  NaN
1040                                                NaN  NaN
1041                                                NaN  NaN
1042                                                NaN  NaN
1043                                                NaN  NaN
1044                                                NaN  NaN
1045                                                NaN  NaN
1046                                                NaN  NaN
1047                                                NaN  NaN
1048                                                NaN  NaN
1049                                                NaN  NaN
1050                                                NaN  NaN
1051                                                NaN  NaN
1052                                                NaN  NaN
1053                                                NaN  NaN
1054                                                NaN  NaN
1055                                                NaN  NaN
1056                                                NaN  NaN
1057                                                NaN  NaN
1058                                                NaN  NaN
1059                                                NaN  NaN
1060                                                NaN  NaN
1061                                                NaN  NaN
1062                                                NaN  NaN
1063                                                NaN  NaN
1064                                                NaN  NaN
1065                                                NaN  NaN
1066                                                NaN  NaN
1067                                                NaN  NaN
1068                                                NaN  NaN
1069                                                NaN  NaN
1070                                                NaN  NaN
1071                                                NaN  NaN
1072                                                NaN  NaN
1073                                                NaN  NaN
1074                                                NaN  NaN
1075                                                NaN  NaN
1076                                                NaN  NaN
1077                                                NaN  NaN
1078                                                NaN  NaN
1079                                                NaN  NaN
1080                                                NaN  NaN
1081                                                NaN  NaN
1082                                                NaN  NaN
1083                                                NaN  NaN
1084                                                NaN  NaN
1085                                                NaN  NaN
1086                                                NaN  NaN
1087                                                NaN  NaN
1088                                                NaN  NaN
1089                                                NaN  NaN
1090                                                NaN  NaN
1091                                                NaN  NaN
1092                                                NaN  NaN
1093                                                NaN  NaN
1094                                                NaN  NaN
1095                                                NaN  NaN
1096                                                NaN  NaN
1097                                                NaN  NaN
1098                                                NaN  NaN
1099                                                NaN  NaN
1100                                                NaN  NaN
1101                                                NaN  NaN
1102                                                NaN  NaN
1103                                                NaN  NaN
1104                                                NaN  NaN
1105                                                NaN  NaN
1106                                                NaN  NaN
1107                                                NaN  NaN
1108                                                NaN  NaN
1109                                                NaN  NaN
1110                                                NaN  NaN
1111                                                NaN  NaN
1112                                                NaN  NaN
1113                                                NaN  NaN
1114                                                NaN  NaN
1115                                                NaN  NaN
1116                                                NaN  NaN
1117                                                NaN  NaN
1118                                                NaN  NaN
1119                                                NaN  NaN
1120                                                NaN  NaN
1121                                                NaN  NaN
1122                                                NaN  NaN
1123                                                NaN  NaN
1124                                                NaN  NaN
1125                                                NaN  NaN
1126                                                NaN  NaN
1127                                                NaN  NaN
1128                                                NaN  NaN
1129                                                NaN  NaN
1130                                                NaN  NaN
1131                                                NaN  NaN
1132                                                NaN  NaN
1133                                                NaN  NaN
1134                                                NaN  NaN
1135                                                NaN  NaN
1136                                                NaN  NaN
1137                                                NaN  NaN
1138                                                NaN  NaN
1139                                                NaN  NaN
1140                                                NaN  NaN
1141                                                NaN  NaN
1142                                                NaN  NaN
1143                                                NaN  NaN
1144                                                NaN  NaN
1145                                                NaN  NaN
1146                                                NaN  NaN
1147                                                NaN  NaN
1148                                                NaN  NaN
1149                                                NaN  NaN
1150                                                NaN  NaN
1151                                                NaN  NaN
1152                                                NaN  NaN
1153                                                NaN  NaN
1154                                                NaN  NaN
1155                                                NaN  NaN
1156                                                NaN  NaN
1157                                                NaN  NaN
1158                                                NaN  NaN
1159                                                NaN  NaN
1160                                                NaN  NaN
1161                                                NaN  NaN
1162                                                NaN  NaN
1163                                                NaN  NaN
1164                                                NaN  NaN
1165                                                NaN  NaN
1166                                                NaN  NaN
1167                                                NaN  NaN
1168                                                NaN  NaN
1169                                                NaN  NaN
1170                                                NaN  NaN
1171                                                NaN  NaN
1172                                                NaN  NaN
1173                                                NaN  NaN
1174                                                NaN  NaN
1175                                                NaN  NaN
1176                                                NaN  NaN
1177                                                NaN  NaN
1178                                                NaN  NaN
1179                                                NaN  NaN
1180                                                NaN  NaN
1181                                                NaN  NaN
1182                                                NaN  NaN
1183                                                NaN  NaN
1184                                                NaN  NaN
1185                                                NaN  NaN
1186                                                NaN  NaN
1187                                                NaN  NaN
1188                                                NaN  NaN
1189                                                NaN  NaN
1190                                                NaN  NaN
1191                                                NaN  NaN
1192                                                NaN  NaN
1193                                                NaN  NaN
1194                                                NaN  NaN
1195                                                NaN  NaN
1196                                                NaN  NaN
1197                                                NaN  NaN
1198                                                NaN  NaN
1199                                                NaN  NaN
1200                                                NaN  NaN
1201                                                NaN  NaN
1202                                                NaN  NaN
1203                                                NaN  NaN
1204                                                NaN  NaN
1205                                                NaN  NaN
1206                                                NaN  NaN
1207                                                NaN  NaN
1208                                                NaN  NaN
1209                                                NaN  NaN
1210                                                NaN  NaN
1211                                                NaN  NaN
1212                                                NaN  NaN
1213                                                NaN  NaN
1214                                                NaN  NaN
1215                                                NaN  NaN
1216                                                NaN  NaN
1217                                                NaN  NaN

Notes: So it looks like there are 1,880 missing values in geo column. The missing values vary across regions and are not location specific. Even though missing values are present in the geo column (and also in lat and long columns), there are enough information in other columns to use to provide location based information (ex: ISO, country, and world_region).

# df_loan_theme

In [38]:
# Import dataframe 
df_loan_theme = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'loan_theme_ids.csv'), index_col = False)

In [39]:
# Check size of dataframe 
df_loan_theme.shape

(779092, 4)

In [43]:
# View dataframe
df_loan_theme.head(30)

        id    Loan Theme ID          Loan Theme Type  Partner ID
0   638631  a1050000000skGl                  General       151.0
1   640322  a1050000000skGl                  General       151.0
2   641006  a1050000002X1ij         Higher Education       160.0
3   641019  a1050000002X1ij         Higher Education       160.0
4   641594  a1050000002VbsW  Subsistence Agriculture       336.0
5   642256  a1050000000T3oX          Extreme Poverty       217.0
6   642311  a1050000000snTK                  General        57.0
7   642353  a1050000000T3oX          Extreme Poverty       217.0
8   642386  a1050000000wf0f                  General       133.0
9   642429  a1050000000wezJ                  General        48.0
10  642836  a1050000000wf0f                  General       133.0
11  643267  a1050000000T3oX          Extreme Poverty       217.0
12  643288  a1050000000wezk                  General        77.0
13  643402  a1050000000wezk                  General        77.0
14  643414  a1050000002VkWz              Underserved       334.0
15  643435  a1050000002VkWz              Underserved       334.0
16  643447  a1050000000shPp          Extreme Poverty        40.0
17  643557  a1050000000skGl                  General       151.0
18  643761  a1050000000wf1a                  General       205.0
19  644101  a1050000000snTK                  General        57.0
20  644518  a1050000000wezq                  General        85.0
21  645222  a1050000000SFvX      Mobile Transactions       219.0
22  645377  a1050000000wf0J                  General       112.0
23  645386  a1050000000wf0J                  General       112.0
24  645758  a1050000000wf19                  General       169.0
25  645781  a1050000000wezq                  General        85.0
26  645846  a1050000000wf19                  General       169.0
27  645918  a1050000000wf19                  General       169.0
28  645927  a1050000000wf19                  General       169.0
29  645953  a1050000000wf19                  General       169.0

In [44]:
# Check descriptive stats 
df_loan_theme.describe()

                 id     Partner ID
count  7.790920e+05  764279.000000
mean   1.047475e+06     180.825840
std    2.282538e+05      97.914029
min    6.386310e+05       9.000000
25%    8.499768e+05     126.000000
50%    1.046528e+06     145.000000
75%    1.244768e+06     204.000000
max    1.444243e+06     557.000000

In [45]:
# Get info 
df_loan_theme.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 779092 entries, 0 to 779091
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               779092 non-null  int64
 1   Loan Theme ID    764279 non-null  object
 2   Loan Theme Type  764279 non-null  object
 3   Partner ID       764279 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 23.8+ MB

In [46]:
# Check for missing values 
df_loan_theme.isnull().sum()

id                     0
Loan Theme ID      14813
Loan Theme Type    14813
Partner ID         14813
dtype: int64

Notes: There are 14,813 missing values in 3 columns. There's a total of 779,092 records. This is relatively small. All of the missing values should be removed since there's no valuable information to fill in the missing values from one column to another except for id.

In [48]:
# Check frequency 
df_loan_theme['Loan Theme Type'].value_counts(dropna = False)

General                                                380693
Underserved                                             62575
Agriculture                                             40108
Rural Inclusion                                         21228
Water                                                   20131
Higher Education                                        17728
General (Women)                                         16566
Vulnerable Populations                                  16354
NaN                                                     14813
Green                                                   13913
Water and Sanitation                                    12032
Startup                                                  9887
Subsistence Agriculture and Solar Lanterns               8597
Youth                                                    8444
Subsistence Agriculture                                  8247
Vulnerable Women                                         8184
FUSAI                                                    6014
Extreme Poverty                                          5475
Murabaha                                                 5264
Disaster Recovery                                        4973
Bridge/Income Smoothing                                  4096
Women Without Poverty                                    3902
Unbanked                                                 3638
Health                                                   3457
Women Entrepreneurs                                      3255
Youth Entrepreneurship                                   3137
Displaced Populations                                    2861
Single mothers                                           2795
Startup (Women)                                          2652
Primary/Secondary Education                              2629
End Consumer Finance                                     2617
Prayas: General                                          2603
Community Impact Loan                                    2151
Conflict Zone                                            2123
Livestock and Fishing                                    2079
Solar Home Systems                                       2077
Mobile Transactions                                      2074
Flexible loan conditions                                 1915
Education                                                1828
Microenterprise (Group)                                  1813
Small Enterprise                                         1723
Senior Citizens                                          1678
Artisan                                                  1627
Housing Improvement                                      1508
Underserved (Women)                                      1413
First/Second Chance                                      1407
Hydrologic                                               1370
At-Risk Youth                                            1340
School Finance                                           1317
Safe Water System for Institution                        1223
SMGBK: General                                           1118
Control Group - Research Study                           1060
Mahashakti: Underserved                                   959
Higher Education (Women)                                  934
Vulnerable Populations (Syrian)                           890
Full Tuition                                              879
SME                                                       867
Agriculture (Women)                                       804
Primary/Secondary Education (Large)                       792
Youth (Women)                                             749
Clean Cookstove                                           713
Clean Energy                                              713
Organic Agriculture                                       712
Education - Kenya                                         668
Vulnerable Populations (Refugees)                         648
Conflict Zone (Gaza)                                      607
BJS: Underserved                                          510
Micro-enterprise                                          494
Sanitation                                                464
Subsistence Agriculture and Solar Lanterns-Tanzania       434
Micro-grid                                                414
Apani: General                                            407
Rural Conflict Zone                                       402
Distributor Finance                                       400
Laptop                                                    399
Mobile transactions - electronic float advance            396
Guardian: Water and Sanitation                            387
Business Development Services                             386
Youth Volunteer's Union                                   378
Underserved (non-Lebanese)                                363
Coffee Production                                         362
Small Business Investment Loan                            343
Imagen Dental                                             336
Asset Finance                                             335
Flexible loan with reduced interest                       323
Gramalaya Microfin Foundation                             323
Agricultural Equipment                                    278
Organic Conversion                                        262
Business in a Box                                         258
Higher Education Murabaha                                 246
Seasonal Worker                                           233
Franchise Package                                         231
PAT                                                       224
Vulnerable Populations (Palestinian)                      222
Gram Utthan: Sanitation                                   217
Retailer Finance                                          211
Vocational Training                                       208
FUSAI Water and Sanitation                                198
Finance to Cooperative                                    193
Panama                                                    186
Single mothers entrepreneurs                              180
Green Murabaha                                            175
Chanura: General                                          171
Value Chain                                               158
Higher Education for Vulnerable Groups                    152
Qard Hassan                                               151
Zaf̬n                                                     147
Prayas: Water and Sanitation                              141
Conflict Zone (Gaza Businesses)                           136
Kubo Experiment - No credit history                       133
Agricultural Labor                                        131
Reduced Interest Rate                                     130
Biodigester                                               128
Indigenous Communities                                    126
Disabled Entrepreneurs                                    126
MESP                                                      125
Salaried Workers                                          121
Biogas                                                    109
Home Energy Conservation                                  106
Low income students                                       104
Mahashakti: Education                                     103
Promesa                                                   101
Graduating Agriculture Loan                                96
Ninh Binh Women's Union                                    90
Field Renewal                                              87
Kiva City Newark                                           86
Education Technology                                       79
Microforestry                                              76
Inventory                                                  76
Education - Cambodia                                       70
Haiti                                                      69
Displaced Populations2                                     69
Hai Duong Women's Union                                    66
Solar refrigerator                                         62
Mobile transactions - capital growth loan.                 60
Sustainable Solar Service Package                          59
Sabuj Sangha                                               59
Women micro-business                                       56
Sustainable farming activities                             54
Murabaha Youth                                             53
Agricultural Infrastructure                                51
Vocational High School                                     50
Vulnerable Populations (Refugees)2                         50
Swayamshree: Green                                         50
Kiva City LA                                               47
Cacao Field Renewal                                        47
Cacao Production                                           45
Equipment Purchase                                         42
Women in agriculture                                       42
Microfranchise                                             42
Vulnerable Populations (Syrian)2                           41
Sahaja Samrudha                                            37
Future Greens Samsthe                                      36
Solar Lamps                                                35
Female headed households                                   31
Startup Murabaha                                           31
Bee Hive                                                   28
Vulnerable Populations2                                    28
Laptop (Refugee)                                           28
Veterans                                                   27
Village Bank                                               23
Swayamshree: General                                       21
Silvopasture                                               21
Clean Water Franchise                                      21
Vulnerable Populations (Syrian)3                           21
MASS                                                       20
Islamic Product                                            20
Vulnerable Populations (Refugees)3                         19
Recycled material activities                               18
Startup (Youth)                                            15
Solar electric fence                                       14
Partial Tuition                                            14
Vulnerable Populations3                                    14
Human Capital Contracts                                    11
Tool Box Loan                                              11
Communities affected by War                                10
Kiva City D.C.                                             10
WLIFT                                                      10
Underserved (large)                                         9
WLIFT-Conflict Zone                                         9
Conflict Zone (Women)                                       8
Distributor Finance - India                                 8
Agroforesty: Plantation Maintenance                         7
Clients below the poverty line                              7
Vulnerable Populations (Physical Disabilities)              6
FUSAI Green                                                 6
Cluster Enterprise Development                              6
Agroforestry: Plantation Establishment                      6
Driptech                                                    5
Clean Water Delivery                                        5
Solar water pump                                            5
Intercropping                                               5
Profit-linked debt                                          4
Passion Fruit Production                                    3
UBER Drivers                                                3
Detroit                                                     3
Redemption                                                  3
CPO - LKM                                                   3
CAMEO Partnership                                           2
WLIFT-Youth                                                 2
Motorbike                                                   2
Property Rights                                             1
SME (Tanzania)                                              1
Vulnerable Populations (Iraqi)                              1
Name: Loan Theme Type, dtype: int64

Notes: Seems like some of the loan theme types are women-specific. Create a flag to note loan theme type to idenify women specific groups.

In [53]:
# Drop rows with missing values 
df_loan_theme.dropna(inplace = True)

In [54]:
# Check size of dataframe 
df_loan_theme.shape

(764279, 4)

Notes: Missing values have been successfully dropped from the dataframe. For reference: 779,092 - 14,813 = 764,279.

## df_loan_theme_region

In [58]:
# Import dataframe 
df_loan_theme_region = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'loan_themes_by_region.csv'), index_col = False)

In [59]:
# View dataframe 
df_loan_theme_region.head(20)

,Partner ID,Field Partner Name,sector,Loan Theme ID,Loan Theme Type,country,forkiva,region,geocode_old,ISO,...,amount,LocationName,geocode,names,geo,lat,lon,mpi_region,mpi_geo,rural_pct
0,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Banteay Meanchey,"(13.75, 103.0)",KHM,...,450,"Banteay Meanchey, Cambodia","[(13.6672596, 102.8975098)]",Banteay Meanchey Province; Cambodia,"(13.6672596, 102.8975098)",13.667260,102.897510,"Banteay Mean Chey, Cambodia","(13.6672596, 102.8975098)",90.0
1,9,KREDIT Microfinance Institution,General Financial Inclusion,a10500000068jPe,Vulnerable Populations,Cambodia,No,Battambang Province,NaN,KHM,...,20275,"Battambang Province, Cambodia","[(13.0286971, 102.989615)]",Battambang Province; Cambodia,"(13.0286971, 102.989615)",13.028697,102.989615,"Banteay Mean Chey, Cambodia","(13.6672596, 102.8975098)",90.0
2,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Battambang Province,NaN,KHM,...,9150,"Battambang Province, Cambodia","[(13.0286971, 102.989615)]",Battambang Province; Cambodia,"(13.0286971, 102.989615)",13.028697,102.989615,"Banteay Mean Chey, Cambodia","(13.6672596, 102.8975098)",90.0
3,9,KREDIT Microfinance Institution,General Financial Inclusion,a10500000068jPe,Vulnerable Populations,Cambodia,No,Kampong Cham Province,"(12.0, 105.5)",KHM,...,604950,"Kampong Cham Province, Cambodia","[(12.0982918, 105.3131185)]",Kampong Cham Province; Cambodia,"(12.0982918, 105.3131185)",12.098292,105.313119,"Kampong Cham, Cambodia","(11.9924294, 105.4645408)",90.0
4,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000002X1Uu,Sanitation,Cambodia,No,Kampong Cham Province,"(12.0, 105.5)",KHM,...,275,"Kampong Cham Province, Cambodia","[(12.0982918, 105.3131185)]",Kampong Cham Province; Cambodia,"(12.0982918, 105.3131185)",12.098292,105.313119,"Kampong Cham, Cambodia","(11.9924294, 105.4645408)",90.0
5,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Kampong Cham Province,"(12.0, 105.5)",KHM,...,62225,"Kampong Cham Province, Cambodia","[(12.0982918, 105.3131185)]",Kampong Cham Province; Cambodia,"(12.0982918, 105.3131185)",12.098292,105.313119,"Kampong Cham, Cambodia","(11.9924294, 105.4645408)",90.0
6,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000007VvXr,Solar Home Systems,Cambodia,No,Kampong Cham Province,"(12.0, 105.5)",KHM,...,1300,"Kampong Cham Province, Cambodia","[(12.0982918, 105.3131185)]",Kampong Cham Province; Cambodia,"(12.0982918, 105.3131185)",12.098292,105.313119,"Kampong Cham, Cambodia","(11.9924294, 105.4645408)",90.0
7,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000weyk,General,Cambodia,No,Kampong Chhnang Province,"(12.0, 104.5)",KHM,...,237175,"Kampong Chhnang Province, Cambodia","[(12.1392352, 104.5655273)]",Kampong Chhnang Province; Cambodia,"(12.1392352, 104.5655273)",12.139235,104.565527,"Kampong Chhnang, Cambodia","(12.1392352, 104.5655273)",90.0
8,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000007VvXr,Solar Home Systems,Cambodia,No,Kampong Chhnang Province,"(12.0, 104.5)",KHM,...,3050,"Kampong Chhnang Province, Cambodia","[(12.1392352, 104.5655273)]",Kampong Chhnang Province; Cambodia,"(12.1392352, 104.5655273)",12.139235,104.565527,"Kampong Chhnang, Cambodia","(12.1392352, 104.5655273)",90.0
9,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Kampong Chhnang Province,"(12.0, 104.5)",KHM,...,31425,"Kampong Chhnang Province, Cambodia","[(12.1392352, 104.5655273)]",Kampong Chhnang Province; Cambodia,"(12.1392352, 104.5655273)",12.139235,104.565527,"Kampong Chhnang, Cambodia","(12.1392352, 104.5655273)",90.0
10,9,KREDIT Microfinance Institution,General Financial Inclusion,a10500000068jPe,Vulnerable Populations,Cambodia,No,Kampong Chhnang Province,"(12.0, 104.5)",KHM,...,323950,"Kampong Chhnang Province, Cambodia","[(12.1392352, 104.5655273)]",Kampong Chhnang Province; Cambodia,"(12.1392352, 104.5655273)",12.139235,104.565527,"Kampong Chhnang, Cambodia","(12.1392352, 104.5655273)",90.0
11,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000002X1Uu,Sanitation,Cambodia,No,Kampong Chhnang Province,"(12.0, 104.5)",KHM,...,1000,"Kampong Chhnang Province, Cambodia","[(12.1392352, 104.5655273)]",Kampong Chhnang Province; Cambodia,"(12.1392352, 104.5655273)",12.139235,104.565527,"Kampong Chhnang, Cambodia","(12.1392352, 104.5655273)",90.0
12,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000002X1Uu,Sanitation,Cambodia,No,Kampong Speu Province,NaN,KHM,...,1000,"Kampong Speu Province, Cambodia","[(11.6155109, 104.3791912)]",Kampong Speu Province; Cambodia,"(11.6155109, 104.3791912)",11.615511,104.379191,"Phnom Penh, Cambodia","(11.5448729, 104.8921668)",90.0
13,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Kampong Speu Province,NaN,KHM,...,15625,"Kampong Speu Province, Cambodia","[(11.6155109, 104.3791912)]",Kampong Speu Province; Cambodia,"(11.6155109, 104.3791912)",11.615511,104.379191,"Phnom Penh, Cambodia","(11.5448729, 104.8921668)",90.0
14,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000weyk,General,Cambodia,No,Kampong Speu Province,NaN,KHM,...,20925,"Kampong Speu Province, Cambodia","[(11.6155109, 104.3791912)]",Kampong Speu Province; Cambodia,"(11.6155109, 104.3791912)",11.615511,104.379191,"Phnom Penh, Cambodia","(11.5448729, 104.8921668)",90.0
15,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Kampot Province,NaN,KHM,...,18650,"Kampot Province, Cambodia","[(10.7412089, 104.1930918)]",Kampot Province; Cambodia,"(10.7412089, 104.1930918)",10.741209,104.193092,"Kampot & Kep, Cambodia","(10.4790637, 104.2941991)",90.0
16,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000weyk,General,Cambodia,No,Kandal Province,"(11.5, 104.8333333)",KHM,...,17025,"Kandal Province, Cambodia","[(11.2237383, 105.1258955)]",Kandal; Cambodia,"(11.2237383, 105.1258955)",11.223738,105.125896,"Kandal, Cambodia","(11.2237383, 105.1258955)",90.0
17,9,KREDIT Microfinance Institution,General Financial Inclusion,a10500000068jPe,Vulnerable Populations,Cambodia,No,Kandal Province,"(11.5, 104.8333333)",KHM,...,68075,"Kandal Province, Cambodia","[(11.2237383, 105.1258955)]",Kandal; Cambodia,"(11.2237383, 105.1258955)",11.223738,105.125896,"Kandal, Cambodia","(11.2237383, 105.1258955)",90.0
18,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Kandal Province,"(11.5, 104.8333333)",KHM,...,63250,"Kandal Province, Cambodia","[(11.2237383, 105.1258955)]",Kandal; Cambodia,"(11.2237383, 105.1258955)",11.223738,105.125896,"Kandal, Cambodia","(11.2237383, 105.1258955)",90.0
19,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Kratie Province,NaN,KHM,...,15650,"Kratie Province, Cambodia","[(12.8606299, 105.9699878)]",KratiÍ© Province; Cambodia,"(12.8606299, 105.9699878)",12.860630,105.969988,"Kratie, Cambodia","(12.4896877, 106.0287512)",90.0

Notes: Seems like there are multiple columns.

In [60]:
# Gather info 
df_loan_theme_region.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15736 entries, 0 to 15735
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Partner ID          15736 non-null  int64
 1   Field Partner Name  15736 non-null  object
 2   sector              15736 non-null  object
 3   Loan Theme ID       15736 non-null  object
 4   Loan Theme Type     15736 non-null  object
 5   country             15736 non-null  object
 6   forkiva             15736 non-null  object
 7   region              15736 non-null  object
 8   geocode_old         1200 non-null   object
 9   ISO                 15722 non-null  object
 10  number              15736 non-null  int64
 11  amount              15736 non-null  int64
 12  LocationName        15736 non-null  object
 13  geocode             13662 non-null  object
 14  names               13661 non-null  object
 15  geo                 15736 non-null  object
 16  lat                 13662 non-null  float64
 17  lon                 13662 non-null  float64
 18  mpi_region          15722 non-null  object
 19  mpi_geo             9671 non-null   object
 20  rural_pct           14344 non-null  float64
dtypes: float64(3), int64(3), object(15)
memory usage: 2.5+ MB

In [61]:
# Check size of the dataframe 
df_loan_theme_region.shape

(15736, 21)

In [62]:
# Check for missing values 
df_loan_theme_region.isnull().sum()

Partner ID                0
Field Partner Name        0
sector                    0
Loan Theme ID             0
Loan Theme Type           0
country                   0
forkiva                   0
region                    0
geocode_old           14536
ISO                      14
number                    0
amount                    0
LocationName              0
geocode                2074
names                  2075
geo                       0
lat                    2074
lon                    2074
mpi_region               14
mpi_geo                6065
rural_pct              1392
dtype: int64

Note: There are multiple missing values in geocode_old column. Perhaps this column should be dropped.

In [64]:
# Check for duplicates 
df_loan_theme_region_dups = df_loan_theme_region[df_loan_theme_region.duplicated()]

In [65]:
df_loan_theme_region_dups

Empty DataFrame
Columns: [Partner ID, Field Partner Name, sector, Loan Theme ID, Loan Theme Type, country, forkiva, region, geocode_old, ISO, number, amount, LocationName, geocode, names, geo, lat, lon, mpi_region, mpi_geo, rural_pct]
Index: []

[0 rows x 21 columns]

Notes: There are no duplicates in the dataframe.

In [66]:
# Export dataframes
df_loans.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'df_loans_cleaned.pkl'))

In [67]:
df_loc.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'df_loc_cleaned.pkl'))

In [68]:
df_loan_theme.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'df_loan_theme_cleaned.pkl'))

In [70]:
df_loan_theme_region.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'df_loan_theme_region_cleaned.pkl'))